# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_shorturl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='url_shorturl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=220, unique=True),
        ),
    ]
