# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170531_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_shorturl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='url_shorturl',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
