# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-01 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170531_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_shorturl',
            name='url',
            field=models.CharField(max_length=500, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
